name: CI Workflow

on:
  pull_request

jobs:
  build:
    name: "Check build successfuly"
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: simeis-main
    steps:
      - name: On récup le repo
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: cargo build --verbose --release
      
