name: CI Workflow

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: On récup le repo
        uses: actions/checkout@v4
      - name: on se place au bon endroit
        run: cd ./simeis
      - name: build
        run: cargo build --verbose --release
      
