name: Build Release Assets

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: "Build release binary and doc"
    runs-on: ubuntu-latest

    steps:
      - name: On récup le repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build stripped release binary
        run: bazel build -c opt //simeis-server:stripped_release

      - name: Build documentation
        run: bazel build //doc:manual