name: Code Quality Check

on:
  pull_request:

jobs:
  cargo-quality:
    name: Vérification de la qualité du code Rust
    runs-on: ubuntu-latest

    steps:
      - name: On récup le repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Lancer les tests unitaires (et le check)
        run: bazel test //...

      - name: Vérifier le formatage (fmt)
        run: bazel test @crates//:cargo-fmt

      - name: Lancer clippy
        run: bazel test @crates//:cargo-clippy