name: Code Quality Check

on:
  pull_request:

jobs:
  cargo-quality:
    name: Vérification de la qualité du code Rust
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simeis-main

    steps:
      - name: On récup le repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Récupérer le chemin du cache Bazel
        id: bazel-cache
        run: echo "dir=$(bazel info output_base)/external" >> $GITHUB_OUTPUT

      - name: Mettre en cache les dépendances Bazel
        uses: actions/cache@v4
        with:
          path: ${{ steps.bazel-cache.outputs.dir }}
          key: bazel-v1-${{ runner.os }}-${{ hashFiles('**/MODULE.bazel.lock', '**/Cargo.lock') }}
          restore-keys: |
            bazel-v1-${{ runner.os }}-

      - name: Lancer les tests unitaires
        run: bazel test //simeis-data:unit_tests

      - name: Vérifier le formatage (fmt)
        run: bazel test @crates//:cargo-fmt

      - name: Lancer clippy
        run: bazel test @crates//:cargo-clippy