name: Code Quality Check

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  cargo-quality:
    name: Vérification de la qualité du code Rust
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simeis-main
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Vérifier la compilation
        run: cargo check

      - name: Vérifier le formatage
        run: cargo fmt --check

      - name: Installer cargo-tarpaulin pour la couverture
        run: cargo install cargo-tarpaulin

#      return a xml file in simeis-data
      - name: Vérifier la couverture avec cargo-tarpaulin
        run: cargo tarpaulin -o xml

      - name: Extraire la couverture
        id: coverage
        run: |
          rate=$(grep -oP '(?<=<coverage [^>]*line-rate=")[0-9\.]+' cobertura.xml | head -1)
          echo "rate=$rate" >> $GITHUB_OUTPUT

      - name: Créer un label selon le résultat
        if: ${{ steps.coverage.outputs.rate < 0.50 }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "not enough tests"