name: Rust Code Quality

on:
  pull_request:
    branches:
      - '**'

jobs:
  rust-quality:
    name: Rust Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify compilation
        run: cargo check
        working-directory: ./simeis-main
