name: Rust Code Quality

# Trigger WF on pull requests to any branch
on:
  pull_request:
    branches:
      - '**'

jobs:
  rust-quality:
    name: Rust Quality Checks
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Check Compilation
      - name: Verify compilation
        run: cargo check
        working-directory: ./simeis-main