name: Execute functional tests on pull to main

on:
  pull_request:
    branches:
      - 'main'

jobs:
  cargo-quality:
    name: Execute functional tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simeis-main

    steps:
      - name: On récup le repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.90.0

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Démarrer le server
        run: bazel run //simeis-server:simeis-server &

      - name: Attendre le server
        run: |
          for i in {1..30}; do
            sleep 1
            echo "waiting..."
          done

      - name: Exécuter les tests
        run: pip install -r ../tests/requirement.txt && pytest ../tests/

      - name: Arrêter le server
        run: pkill -f simeis-server